[alembic]
# Path al directorio con scripts de migración
script_location = alembic

# Plantilla para nombres de archivo de migración
file_template = %%(year)d%%(month).2d%%(day).2d_%%(hour).2d%%(minute).2d_%%(slug)s

# Zona horaria
timezone = UTC

# Versiones por carpeta
version_locations = %(here)s/alembic/versions

# La URL real se inyecta desde env.py leyendo settings.database_url
sqlalchemy.url =


[post_write_hooks]


[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
